[build]
node_compat = true
node_version = "20.10.0"
command = "./build.sh"
output_directory = "out"

[build.environment]
NODE_VERSION = "20.10.0"

[[excludes]]
file = ".next/cache/**/*"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200