[build]
node_compat = true
node_version = "20.10.0"
command = "npm run build"
output_directory = "out"

[build.environment]
NODE_VERSION = "20.10.0"

# Handle all routes with index.html for SPA support
[[redirects]]
from = "/*"
to = "/index.html"
status = 200